/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/agenda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Agenda
         * @description Run the Tagesordnung-Vorschlag graph for a given WEG.
         *
         *     Streamed via SSE will come next (§ 4.4); for now we ``ainvoke`` and
         *     return the final ``AgendaVorschlag`` shape directly.
         */
        post: operations["post_agenda_agent_agenda_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/beschluss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Beschluss
         * @description Run the Beschluss-Formulierungs-Prüfung graph on a single draft text.
         */
        post: operations["post_beschluss_agent_beschluss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/protokoll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Or Resume Protokoll
         * @description Run or resume the HITL Protokoll graph.
         *
         *     - Without resume_token: invokes graph, catches GraphInterrupt, returns draft.
         *     - With resume_token:    verifies tenant ownership, resumes with edited_draft,
         *                             returns completed status after persist_node writes the row.
         */
        post: operations["generate_or_resume_protokoll_agent_protokoll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/vorgang": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Vorgang
         * @description Run the Vorgangszentrale suggestion graph.
         */
        post: operations["post_vorgang_agent_vorgang_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/internal/frist-scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Frist Scan
         * @description Nightly scan for upcoming Einladungsfristen (§ 4.4). Stub returns empty results.
         */
        post: operations["frist_scan_agent_internal_frist_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgendaInvokeRequest
         * @description Trigger payload for the agenda graph.
         *
         *     Distinct from ``schemas.AgendaRequest`` (which is the older stub-era
         *     contract). Once the router stabilises this can replace it in
         *     ``app.schemas``.
         */
        AgendaInvokeRequest: {
            /**
             * Weg Id
             * @description UUID-string der WEG, für die die TO vorbereitet wird.
             */
            weg_id: string;
            /**
             * Verwalter Hinweis
             * @description Optionaler Freitext zur Versammlung — 'Beirats-Wahl steht an', 'außerordentliche Versammlung wegen Wasserschaden', etc.
             */
            verwalter_hinweis?: string | null;
        };
        /**
         * AgendaItemSuggestion
         * @description One proposed TOP (Tagesordnungs-Punkt) for the upcoming meeting.
         */
        AgendaItemSuggestion: {
            /**
             * Titel
             * @description Knapper TOP-Titel, max ~80 Zeichen.
             */
            titel: string;
            /**
             * Beschreibung
             * @description Inhalt des TOP — Antragsteller, Beschluss-Gegenstand, geplante Mehrheit (Bestimmtheitsgrundsatz, § 4.6).
             */
            beschreibung: string;
            /**
             * Rationale
             * @description Warum dieser TOP vorgeschlagen wird (z. B. 'wiederkehrend laut Vorjahres-Protokoll TOP 5', 'Branchenstandard', 'Beirats-Wahl alle 2 Jahre § 29 WEG').
             */
            rationale: string;
            /**
             * Quelle
             * @description Herkunft des Vorschlags — speist die UI-Begründungs-Spalte.
             * @enum {string}
             */
            quelle: "vorjahres_protokoll" | "branchenstandard" | "frist_gebunden";
        };
        /**
         * AgendaResponse
         * @description Router response — the structured ``AgendaVorschlag`` + thread_id for traces.
         *
         *     ``vorschlag`` ist bewusst das Graph-Modell selbst: der OpenAPI-Kontrakt
         *     (``just codegen`` → shared-types) trägt damit die volle Payload-Form,
         *     und Drift zwischen Graph und apps/web wird zum Compile-Fehler.
         */
        AgendaResponse: {
            vorschlag: components["schemas"]["AgendaVorschlag"];
            /** Thread Id */
            thread_id: string;
        };
        /**
         * AgendaVorschlag
         * @description Top-level structured response from the agenda graph.
         */
        AgendaVorschlag: {
            /**
             * Items
             * @description Vorgeschlagene TOPs in der gewünschten Reihenfolge.
             */
            items: components["schemas"]["AgendaItemSuggestion"][];
            /**
             * Konfidenz
             * @description Selbstbewertung der Vorschlags-Sicherheit.
             * @enum {string}
             */
            konfidenz: "hoch" | "mittel" | "niedrig";
            /**
             * Fehlende Inputs
             * @description Inputs, die nicht im Kontext lagen, den Vorschlag aber verbessert hätten (z. B. 'Jahresabrechnung-Status').
             */
            fehlende_inputs?: string[];
        };
        /**
         * AgentSuggestion
         * @description Generic suggestion envelope — concrete shapes refine per use-case later.
         */
        AgentSuggestion: {
            /**
             * Suggestion Id
             * Format: uuid
             */
            suggestion_id: string;
            /**
             * Use Case
             * @enum {string}
             */
            use_case: "agenda" | "beschluss" | "frist" | "protokoll" | "vorgang";
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /**
         * BeschlussCheckResponse
         * @description Router response — the structured Befund + the thread_id for trace links.
         *
         *     ``befund`` ist bewusst das Graph-Modell selbst: der OpenAPI-Kontrakt
         *     (``just codegen`` → shared-types) trägt damit die volle Payload-Form,
         *     und Drift zwischen Graph und apps/web wird zum Compile-Fehler.
         */
        BeschlussCheckResponse: {
            befund: components["schemas"]["BestimmtheitsBefund"];
            /** Thread Id */
            thread_id: string;
        };
        /**
         * BeschlussRequest
         * @description Trigger payload for the beschluss graph (§ 4.1, Use-Case 2).
         */
        BeschlussRequest: {
            /**
             * Weg Id
             * Format: uuid
             */
            weg_id: string;
            /** Draft Text */
            draft_text: string;
        };
        /**
         * BestimmtheitsBefund
         * @description Structured verdict on a draft Beschluss per the Bestimmtheitsgrundsatz.
         *
         *     The three booleans are the canonical legal test (Antragsteller,
         *     Beschlussgegenstand, Mehrheitserfordernis). ``redlining_vorschlag`` is
         *     the actionable output for the Verwalter — what they paste back into the
         *     draft to make it bestimmt.
         */
        BestimmtheitsBefund: {
            /**
             * Antragsteller Klar
             * @description Ist der Antragsteller im Wortlaut eindeutig benannt?
             */
            antragsteller_klar: boolean;
            /**
             * Beschlussgegenstand Klar
             * @description Ist der konkrete Beschlussgegenstand aus dem Wortlaut ableitbar?
             */
            beschlussgegenstand_klar: boolean;
            /**
             * Mehrheitserfordernis Klar
             * @description Ist das Mehrheitserfordernis explizit angegeben?
             */
            mehrheitserfordernis_klar: boolean;
            /**
             * Fehlende Elemente
             * @description Knappe Liste der fehlenden oder unklaren Elemente.
             */
            fehlende_elemente?: string[];
            /**
             * Redlining Vorschlag
             * @description Konkrete Umformulierung des Beschluss-Textes, die alle drei Bestimmtheits-Anforderungen erfüllt.
             */
            redlining_vorschlag: string;
            /**
             * Konfidenz
             * @description Selbstbewertung der Prüfsicherheit.
             * @enum {string}
             */
            konfidenz: "hoch" | "mittel" | "niedrig";
        };
        /**
         * FristScanResponse
         * @description Response shape for the internal pg_cron callback (§ 4.4).
         */
        FristScanResponse: {
            /**
             * Status
             * @default stub
             * @constant
             */
            status: "stub";
            /** Scan Results */
            scan_results?: components["schemas"]["AgentSuggestion"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * ProtokollRequest
         * @description Trigger payload for the protokoll graph (§ 4.1, Use-Case 4 — HITL).
         *
         *     Two modes:
         *       - First call:  resume_token=None → graph runs to interrupt, returns draft.
         *       - Resume call: resume_token=thread_id + edited_draft → graph continues, persists.
         */
        ProtokollRequest: {
            /**
             * Meeting Id
             * Format: uuid
             */
            meeting_id: string;
            /**
             * Resume Token
             * @description Set when resuming an interrupted graph via Command(resume=...).
             */
            resume_token?: string | null;
            /**
             * Edited Draft
             * @description Verwalter-edited Markdown text, required when resume_token is set.
             */
            edited_draft?: string | null;
        };
        /**
         * ProtokollResponse
         * @description Router response for both modes of the protokoll endpoint.
         */
        ProtokollResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "awaiting_review" | "completed";
            /** Thread Id */
            thread_id: string;
            /** Draft */
            draft?: string | null;
            /** Konfidenz */
            konfidenz?: ("hoch" | "mittel" | "niedrig") | null;
            /** Fehlende Daten */
            fehlende_daten?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VorgangInvokeRequest
         * @description Trigger payload for the Vorgangszentrale graph.
         */
        VorgangInvokeRequest: {
            /**
             * User Request
             * @description Freitext-Auftrag des Verwalters.
             */
            user_request: string;
            /** Vorgang Id */
            vorgang_id?: string | null;
            /** Inbox Item Id */
            inbox_item_id?: string | null;
            /** Weg Id */
            weg_id?: string | null;
            /**
             * Suggestion Type
             * @description Optionaler UI-Hinweis auf die erwartete Vorschlagsart.
             */
            suggestion_type?: ("vorgang_triage" | "antwort_entwurf" | "frist_vorschlag" | "dokument_metadaten_vorschlag" | "tool_action_proposal" | "rag_answer" | "blocked_proposal") | null;
        };
        /**
         * VorgangResponse
         * @description Router response — structured suggestion plus thread id for traces.
         */
        VorgangResponse: {
            /** Suggestion */
            suggestion: {
                [key: string]: unknown;
            };
            /** Thread Id */
            thread_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    post_agenda_agent_agenda_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Bearer <user_jwt> */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgendaInvokeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgendaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_beschluss_agent_beschluss_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Bearer <user_jwt> */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeschlussRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeschlussCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_or_resume_protokoll_agent_protokoll_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Bearer <user_jwt> */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProtokollRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtokollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_vorgang_agent_vorgang_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Bearer <user_jwt> */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VorgangInvokeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VorgangResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    frist_scan_agent_internal_frist_scan_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Bearer <agent_internal_token> */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FristScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
