import { test as setup, expect } from "@playwright/test";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { resolve } from "node:path";

// Authenticated setup — one-time per Playwright run:
//   1. Idempotently seed an admin tenant + tenant_admin user against the
//      linked Cloud Frankfurt project via `apps/web/scripts/seed-admin.mjs`.
//   2. Log in through the real /login form so the session cookies are
//      generated by the same Server Action stack that production uses.
//   3. Persist storage state to `playwright/.auth/admin.json` so every
//      subsequent project can attach those cookies via `use.storageState`.
//
// Specs that need an authenticated browser declare `dependencies: ["setup"]`
// in playwright.config.ts and consume the saved state. Specs that should
// remain anonymous (the negative-credentials login test) opt out with
// `test.use({ storageState: { cookies: [], origins: [] } })`.

const execFileAsync = promisify(execFile);
const webDir = process.cwd();
const seedScript = resolve(webDir, "scripts", "seed-admin.mjs");

export const STORAGE_STATE_PATH = resolve(webDir, "playwright", ".auth", "admin.json");
export const TENANT_B_STORAGE_STATE_PATH = resolve(webDir, "playwright", ".auth", "tenant_b.json");

// Defaults baked into seed-admin.mjs at the time of writing — keep these in
// sync with that script's `emailArg || …` / `passwordArg || …` fallbacks.
export const ADMIN_EMAIL = "admin@admin.com";
export const ADMIN_PASSWORD = "admin1";

export const TENANT_B_EMAIL = "tenant_b@admin.com";
export const TENANT_B_PASSWORD = "admin1";
export const TENANT_B_NAME = "Secondary WEG-Verwaltung";
export const TENANT_B_ROLE = "verwalter_mitarbeiter";

setup("authenticate as seeded admin", async ({ page }) => {
  // Seed first. The script handles the "user already registered" path by
  // looking up the existing auth user and upserting the tenant_member row.
  const { stderr } = await execFileAsync("node", [seedScript], { cwd: webDir });
  if (stderr.trim()) console.warn("[seed-admin stderr]", stderr);

  await page.goto("/login");
  await page.getByLabel("E-Mail").fill(ADMIN_EMAIL);
  await page.getByLabel("Passwort").fill(ADMIN_PASSWORD);
  await page.getByRole("button", { name: /anmelden/i }).click();

  // The dashboard redirect proves a session cookie was set; saving here
  // captures both the supabase-* auth cookies and the next-route cookies.
  await expect(page).toHaveURL(/\/dashboard/, { timeout: 15_000 });
  await page.context().storageState({ path: STORAGE_STATE_PATH });
});
setup("authenticate as seeded secondary tenant (Tenant B)", async ({ page }) => {
  const { stderr } = await execFileAsync(
    "node",
    [seedScript, TENANT_B_EMAIL, TENANT_B_PASSWORD, TENANT_B_NAME, TENANT_B_ROLE],
    { cwd: webDir }
  );
  if (stderr.trim()) console.warn("[seed-admin Tenant B stderr]", stderr);

  await page.goto("/login");
  await page.getByLabel("E-Mail").fill(TENANT_B_EMAIL);
  await page.getByLabel("Passwort").fill(TENANT_B_PASSWORD);
  await page.getByRole("button", { name: /anmelden/i }).click();

  await expect(page).toHaveURL(/\/dashboard/, { timeout: 15_000 });
  await page.context().storageState({ path: TENANT_B_STORAGE_STATE_PATH });
});
